ROLE_SKILL_MAP = {
    "Software Developer": ["python", "oop", "git", "api design"],
    "Web Developer": ["html", "css", "javascript", "http"],
    "Backend Developer": ["python", "django", "rest", "databases"],
    "Frontend Developer": ["javascript", "react", "html", "css"],
    "Full Stack Developer": ["javascript", "react", "python", "django", "sql"],
    "Data Scientist": ["python", "statistics", "machine learning", "data visualization"],
    "Data Analyst": ["sql", "pandas", "data analysis", "excel"],
    "Machine Learning Engineer": ["python", "statistics", "machine learning", "scikit-learn", "model deployment"],
    "AI Engineer": ["python", "deep learning", "nlp", "model deployment"],
    "Cloud Engineer": ["aws", "docker", "kubernetes", "cloud"],
    "DevOps Engineer": ["linux", "ci/cd", "docker", "monitoring"],
    "Cyber Security Analyst": ["network security", "vulnerability assessment", "incident response"],
    "Mobile App Developer": ["android", "kotlin", "mobile", "ui design"],
    "System Engineer": ["linux", "networks", "scripting", "monitoring"],
}

SKILL_METADATA = {
    "python": {
        "level": "Foundation",
        "topics": ["Syntax", "Functions", "OOP", "Modules"],
        "prerequisites": [],
        "eta_weeks": 2,
        "assessment_type": ["MCQ", "Coding"],
    },
    "statistics": {
        "level": "Foundation",
        "topics": ["Probability", "Distributions", "Hypothesis Testing"],
        "prerequisites": [],
        "eta_weeks": 3,
        "assessment_type": ["MCQ", "Case Study"],
    },
    "sql": {
        "level": "Foundation",
        "topics": ["SELECT", "JOIN", "Aggregation", "Indexes"],
        "prerequisites": [],
        "eta_weeks": 2,
        "assessment_type": ["MCQ", "Coding"],
    },
    "javascript": {
        "level": "Foundation",
        "topics": ["ES6", "DOM", "Async Programming"],
        "prerequisites": [],
        "eta_weeks": 3,
        "assessment_type": ["MCQ", "Coding"],
    },
    "machine learning": {
        "level": "Core",
        "topics": ["Regression", "Classification", "Clustering"],
        "prerequisites": ["python", "statistics"],
        "eta_weeks": 4,
        "assessment_type": ["MCQ", "Case Study"],
    },
    "scikit-learn": {
        "level": "Core",
        "topics": ["Pipelines", "Feature Engineering", "Model Selection"],
        "prerequisites": ["python", "machine learning"],
        "eta_weeks": 2,
        "assessment_type": ["Coding", "Case Study"],
    },
    "model deployment": {
        "level": "Advanced",
        "topics": ["APIs", "Model Serving", "Monitoring"],
        "prerequisites": ["python"],
        "eta_weeks": 3,
        "assessment_type": ["Project"],
    },
    "deep learning": {
        "level": "Advanced",
        "topics": ["Neural Networks", "CNN", "RNN"],
        "prerequisites": ["machine learning", "python"],
        "eta_weeks": 3,
        "assessment_type": ["Project"],
    },
    "nlp": {
        "level": "Advanced",
        "topics": ["Tokenization", "Embeddings", "Transformers"],
        "prerequisites": ["python", "machine learning"],
        "eta_weeks": 3,
        "assessment_type": ["Project", "Case Study"],
    },
    "django": {
        "level": "Core",
        "topics": ["Models", "Views", "REST APIs"],
        "prerequisites": ["python"],
        "eta_weeks": 2,
        "assessment_type": ["Coding", "Project"],
    },
    "rest": {
        "level": "Core",
        "topics": ["HTTP", "Serialization", "Auth"],
        "prerequisites": ["django"],
        "eta_weeks": 2,
        "assessment_type": ["MCQ", "Coding"],
    },
    "react": {
        "level": "Core",
        "topics": ["Components", "Hooks", "State Management"],
        "prerequisites": ["javascript"],
        "eta_weeks": 3,
        "assessment_type": ["Coding", "Project"],
    },
    "docker": {
        "level": "Core",
        "topics": ["Images", "Containers", "Compose"],
        "prerequisites": [],
        "eta_weeks": 2,
        "assessment_type": ["Case Study", "Project"],
    },
    "kubernetes": {
        "level": "Advanced",
        "topics": ["Pods", "Services", "Deployments"],
        "prerequisites": ["docker"],
        "eta_weeks": 3,
        "assessment_type": ["Project"],
    },
    "aws": {
        "level": "Core",
        "topics": ["EC2", "S3", "IAM"],
        "prerequisites": [],
        "eta_weeks": 3,
        "assessment_type": ["Case Study", "Project"],
    },
    "linux": {
        "level": "Foundation",
        "topics": ["CLI", "Permissions", "Processes"],
        "prerequisites": [],
        "eta_weeks": 2,
        "assessment_type": ["MCQ", "Coding"],
    },
    "ci/cd": {
        "level": "Core",
        "topics": ["Pipelines", "Testing", "Deployment"],
        "prerequisites": ["linux"],
        "eta_weeks": 2,
        "assessment_type": ["Case Study"],
    },
    "network security": {
        "level": "Core",
        "topics": ["Threats", "Firewalls", "IDS"],
        "prerequisites": [],
        "eta_weeks": 3,
        "assessment_type": ["MCQ", "Case Study"],
    },
    "vulnerability assessment": {
        "level": "Core",
        "topics": ["Scanning", "Reporting", "Mitigation"],
        "prerequisites": ["network security"],
        "eta_weeks": 2,
        "assessment_type": ["Case Study"],
    },
    "incident response": {
        "level": "Advanced",
        "topics": ["Detection", "Containment", "Recovery"],
        "prerequisites": ["network security"],
        "eta_weeks": 2,
        "assessment_type": ["Case Study"],
    },
}

DEFAULT_SKILL_TEMPLATE = {
    "level": "Core",
    "topics": ["Basics", "Intermediate Concepts", "Best Practices"],
    "prerequisites": [],
    "eta_weeks": 2,
    "assessment_type": ["MCQ"],
}
