# Generated by Django 6.0.2 on 2026-02-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MongoExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Mongo Skill Extraction',
                'verbose_name_plural': 'Mongo Skill Extractions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MongoPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Mongo Role Prediction',
                'verbose_name_plural': 'Mongo Role Predictions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MongoResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Mongo Resume',
                'verbose_name_plural': 'Mongo Resumes',
                'managed': True,
            },
        ),
    ]
